apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: low-priority-pod
  name: low-priority-pod
  namespace: phase-1
spec:
  replicas: 6
  selector:
    matchLabels:
      app: low-priority-pod
  strategy: {}
  template:
    metadata:
      labels:
        app: low-priority-pod
        priority: low
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: priority
                      operator: In
                      values:
                        - low
                topologyKey: "kubernetes.io/hostname"
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/openshift/httpd
          name: httpd
          resources:
            requests:
              memory: "2000Mi"
