apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: low-priority-pod
  name: low-priority-pod
  namespace: phase-1
spec:
  replicas: 5
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: app
            operator: In
            values:
              - low-priority-pod
  selector:
    matchLabels:
      app: low-priority-pod
  strategy: {}
  template:
    metadata:
      labels:
        app: low-priority-pod
    spec:
      containers:
        - image: busybox
          name: busybox
          command: [ "sleep" ]
          args: [ "infinity" ]
          resources:
            requests:
              memory: "2000Mi"
