apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: benchwarmer-mz-pod
  name: benchwarmer-mz-pod
  namespace: benchwarming-multizone-autoscaling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benchwarmer-mz-pod
  strategy: {}
  template:
    metadata:
      labels:
        app: benchwarmer-mz-pod
        priority: low
    spec:
      priorityClassName: low-priority
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - benchwarmer-mz-pod
              topologyKey: "topology.kubernetes.io/zone"
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: NotIn
                    values:
                      - benchwarmer-mz-pod
              topologyKey: "kubernetes.io/hostname"
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - benchwarmer-mz-pod
              topologyKey: "kubernetes.io/hostname"
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/openshift/httpd
          name: httpd
